-- Insertar categorías de platos
INSERT INTO dish_categories (id, name, description) VALUES
(UUID(), 'Entradas', 'Aperitivos y platos para comenzar'),
(UUID(), 'Platos Principales', 'Platos fuertes y principales'),
(UUID(), 'Postres', 'Dulces y postres'),
(UUID(), 'Bebidas', 'Bebidas alcohólicas y no alcohólicas'),
(UUID(), 'Ensaladas', 'Ensaladas frescas y saludables'),
(UUID(), 'Sopas', 'Sopas calientes y frías'),
(UUID(), 'Pizzas', 'Pizzas de diferentes estilos'),
(UUID(), 'Hamburguesas', 'Hamburguesas y sándwiches'),
(UUID(), 'Mariscos', 'Platos de pescado y mariscos'),
(UUID(), 'Carnes', 'Platos de carne roja y blanca'),
(UUID(), 'Pasta', 'Platos de pasta italiana'),
(UUID(), 'Comida Asiática', 'Platos de cocina asiática'),
(UUID(), 'Comida Mexicana', 'Platos de cocina mexicana'),
(UUID(), 'Desayunos', 'Platos para el desayuno'),
(UUID(), 'Snacks', 'Bocadillos y aperitivos ligeros'),
(UUID(), 'Comida Rápida', 'Fast food y comida para llevar'),
(UUID(), 'Comida Saludable', 'Opciones bajas en calorías y nutritivas'),
(UUID(), 'Comida Vegana', 'Platos 100% veganos'),
(UUID(), 'Sin Gluten', 'Opciones libres de gluten');
